#!/bin/bash
export demo_root=$1
export num_events=$2
export JAVA_HOME=$3



cd ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-data-simulator/target
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-1.txt 10 'Saint Louis to Tulsa' > nohup-telemetry-device-1.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-2.txt 11 'Saint Louis to Chicago' > nohup-telemetry-device-2.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-3.txt 12 'Saint Louis to Memphis' > nohup-telemetry-device-3.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-4.txt 13 'Des Moines to Chicago' > nohup-telemetry-device-4.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-5.txt 14 'Joplin to Kansas City' > nohup-telemetry-device-5.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-6.txt 15 'Memphis to Little Rock' > nohup-telemetry-device-6.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-7.txt 16 'Peoria to Ceder Rapids' > nohup-telemetry-device-7.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-8.txt 17 'Springfield to KC Via Columbia' > nohup-telemetry-device-8.out  &
nohup java -jar stream-simulator-jar-with-dependencies.jar '' -1 hortonworks.hdp.refapp.trucking.simulator.impl.domain.transport.Truck hortonworks.hdp.refapp.trucking.simulator.impl.collectors.FileEventCollector 1 ${demo_root}/hdp/reference-apps/iot-trucking-app/trucking-web-portal/src/main/resources/routes/midwest ${num_events} /tmp/truck-sensor-data/telemetry-device-9.txt 18 'Springfield to KC Via Hanibal' > nohup-telemetry-device-9.out  &


